version: '3'

services:
    app:
        build: .
        image: app:latest
        command: flask run -h 0.0.0.0
        container_name: notification_system
        env_file:
            - .flaskenv
        ports: 
            - "5000:5000"
        volumes: 
            - .:/notification_service
        depends_on: 
            - mymongo
            - redis-server
        networks:
            - backend
    
    mymongo:
        image: mongo:latest
        container_name: mymongo
        networks:
            - backend
    
    redis-server:
        image: redis:latest
        container_name: redis-server
        networks:
            - backend

    redis-worker-db:
        image: app:latest
        command: rq worker --url redis://redis-server:6379 db-jobs
        env_file:
            - .flaskenv
        depends_on: 
            - redis-server
        networks: 
            - backend
    
    redis-worker-webpush:
        image: app:latest
        command: rq worker --url redis://redis-server:6379 webpush-jobs
        env_file:
            - .flaskenv
        depends_on: 
            - redis-server
        networks: 
            - backend

    redis-worker-publish:
        image: app:latest
        command: rq worker --url redis://redis-server:6379 publish-jobs
        env_file:
            - .flaskenv
        depends_on: 
            - redis-server
        networks: 
            - backend

networks:
    backend:
        